### ISSUE TITLE
Fix interference between WS2812 library and V-USB

### ISSUE THREAD

**Issue by sowbug** [sowbug/usb-led#13]
V-USB really doesn't want anyone else using interrupts. Switch to micronucleus 2.0?

**Comment by sowbug** [comment]
Might need to do this by switching light to APA102C. It's hard to have two timing-sensitive components coexist peacefully.

**Comment by Bluebie** [comment]
ws2812 LEDs do not require you update then with a specific frequency. They can be send a colour and they will internally hold that rgb value with their own internal free running PWM controller. I'm a bit confused why weblight even uses interrupts to drive this.

You might like to look at littlewire.cc - it supports outputting to large ws2812 strands and runs on interrupt v-usb on attiny85. Your StatusBlink function in led_control.c might give you some trouble though, as those long delay loops will block your main event loop for a long while and could be disruptive to USB. Generally if you're going to block your event loop for more than about 50ms you really need to be calling usbPoll in your delay loop and using timers, like this: https://github.com/digistump/DigisparkArduinoIntegration/blob/master/libraries/DigisparkUSB/DigiUSB.cpp#L96

**Comment by Bluebie** [comment]
something of note: the way littlewire deals with timing is similar to micronucleus in a way - it only ever sends colours to the leds in response to a usb command. because usb only updates at 1khz, when you recieve a command you know you have about 1000ns to do whatever you like without getting any usb-related interrupts messing up your timing. turns out that's plenty of time to update some LEDs. If for some reason you want to persistently be updating them (animating them device side?) you could perhaps do that work at the end of the usb interrupt handler? or set a flag that the interrupt handler resets which gives the event loop permission to update the LEDs again? that way you'd have a piece of code running at 1khz with time to mess around uninterrupted, even when no commands are being sent. USB idles with a 1khz pulse that acts as a sort of keep alive and timing signal.

**Comment by sowbug** [comment]
Thank you for your insight, @Bluebie! I misspoke in the original issue description. What I meant to say is that V-USB doesn't want anyone else messing around with the interrupt system. What I observed in my initial experiments was that if I updated the WS2812s too often (exactly the device-side animation you're speculating about), I'd start to see I/O errors with USB -- sometimes a string descriptor request would fail, etc. I wasn't updating the lights in a timer or an interrupt routine, but I was updating them frequently.

I noticed that the I/O errors happened more frequently if I updated both LEDs rather than just one, and this was the clue I needed to figure out that because the WS2812 library called cli() before doing its business, it was stealing real-time code execution that V-USB needed, which was messing around with the USB servicing. (Understand that at this point I couldn't rule out anything -- memory smasher, bad hardware design on my prototype board, misusing the V-USB code, etc., so this was just one of several theories what was wrong.)

For a while I simply left interrupts enabled in the WS2812 code, which definitely fixed the I/O errors, but it made light updates unreliable at worst, and flickery at best (all as expected).

I ended up separating the concept of setting the LED colors in the RGB SRAM buffer from sending that buffer to the physical LEDs, and then throwing the sending code into USB_POST_TX_HOOK (https://github.com/sowbug/weblight/blob/master/firmware/usbconfig.h#L145), reasoning that if USB was a request-response model, which I think it is for the kinds of data I'm using, then I was likely to be able to briefly shut off interrupts and run the WS2812 code right after sending my responses. So far, this has worked quite well, but I didn't know enough about USB to feel that this was a robust approach.

If I'm reading your suggestions correctly, then my current solution might be reasonable. I'll think about your idea of updating in the main event loop after the interrupt has run -- that's similar in principle to what I had done, but it feels better because I know it'll fire at 1kHz.

(BTW StatusBlink() is only for debugging -- basically "yes this line of code ran!" -- and at that point I'm no longer caring about anything else. But it'd be very cool to make even that work, and I'll experiment with the DigiUSB method of delaying safely.)

Thanks again!

**Comment by sowbug** [comment]
More on USB_POST_TX_HOOK, which might have had you saying "huh?":

https://github.com/sowbug/weblight/commit/db749fba1cc9da55c094c4623d357246b030b4ab

**Comment by Bluebie** [comment]
oh the request-response thing: that's correct. I'm not sure about higher speed versions of USB, but for low speed devices like these, USB has a very strict architecture. Devices never initiate communication. USB "interrupts" work by setting a flag which the host reads as part of that 1khz polling message, then if the host sees that, it should request the interrupt message on it's own schedule.

The only catch with using that 1000kz polling signal to drive lighting updates is that if the host goes to sleep, the polling will stop, so your animation could freeze. If you wanted to be super fancy you could detect that with a timer and fade the lights out when the computer goes to sleep or switch to using an internal timer to drive the animation till the host wakes up.

**Comment by sowbug** [comment]
Ugh, sleep. You're many steps ahead of me (which is great because you're saving me design/debugging time). So I guess the logic could be something like this:

```
// Somewhere in main loop
if (animation_timer_has_expired) {
  if (host_is_asleep) {
    animate_lights_and_reset_timer();
  } else {
    if (vusb_interrupt_ran) {
      animate_lights_and_reset_timer();
    }
  }
}
// Reset this each time through loop because when host is awake,
// we want to update lights only ASAP after the interrupt.
vusb_interrupt_ran = false;
```

I could probably tighten up that logic, but I think this carries out what you're saying.

**Comment by sowbug** [comment]
This is about as fixed as it needs to be. As we add more features, we will figure out how to fit them into the small time slice after the USB host heartbeat.

**Comment by Bluebie** [comment]
pseudocode looks reasonable to me. 👍
