### ISSUE TITLE
Chrome WebUSB can't handle PROGMEM descriptors

### ISSUE THREAD

**Issue by sowbug** [sowbug/usb-led#25]
For some strange reason, Chrome won't recognize a device after this patch has been applied:

https://github.com/sowbug/weblight/commit/c73be82dbb46d73e690398a7780dd4b102112e7c

Other USB tools seem to handle it just fine, and WinUSB descriptors work fine on Windows. What's going on? @reillyeon, any idea?

**Comment by sowbug** [comment]
@reillyeon

**Comment by reillyeon** [comment]
Not sure but I can throw my USB analyzer at it. Your change looks isomorphic to the existing WinUSB code so it should be working.

**Comment by sowbug** [comment]
I just dropped off a green board on your desk. It's flashed with https://github.com/sowbug/weblight/commit/c73be82dbb46d73e690398a7780dd4b102112e7c and thus demonstrates the bug.

**Comment by reillyeon** [comment]
It appears that both WebUSB control transfers time out. The first one is sent to the device but no response is received.

**Comment by sowbug** [comment]
Still investigating.
