### ISSUE TITLE
WebLight demo page doesn't handle multiple devices at once

### ISSUE THREAD

**Issue by sowbug** [sowbug/usb-led#41]
Plug in two WebLights that are configured to connect to https://sowbug.github.io/weblight/. If necessary, pair them. Note that the two control divs on the page have the same serial number, and they control only one of the two devices.

I've skimmed https://github.com/sowbug/weblight/blob/gh-pages/weblight.js and don't see anything obviously wrong. I know this used to work. Has anything changed?

**Comment by reillyeon** [comment]
Confirmed, something weird is happening.
