### ISSUE TITLE
Can you buy these anywhere?

### ISSUE THREAD

**Issue by auchenberg** [sowbug/usb-led#45]
I'm organizer of ColdFront conference, https://2017.coldfront.co, and we'd love to give our attendees a WebUSB board. 

Can you buy these anywhere?

**Comment by sowbug** [comment]
How many do you need? I have a very small batch and might be able to get
you some.

**Comment by auchenberg** [comment]
Ideally I'd need 200-300 to give everyone one, but it depends on the cost price, etc.

**Comment by sowbug** [comment]
I'll see what I can do. We don't have that many, and for various reasons
it's hard to sell them -- only give them away.

**Comment by auchenberg** [comment]
I understand, and thanks! We have Kenneth from Intel speaking about WebUSB, and are in the talks with Google (Robert Nyman) of potential sponsoring some WebUSB hardware to folks. 

Can I reach you on email, or is it best to keep this issue open?

**Comment by sowbug** [comment]
Please email me at my google.com address (miket) and then we can close this
public issue.

**Comment by sowbug** [comment]
Contacted offline
